FROM balenalib/%%BALENA_ARCH%%-debian:bookworm
LABEL maintainer="https://github.com/ketilmo"

ENV RADARBOX_KEY=

ARG PERM_INSTALL="tini python3 python3-fastapi python3-uvicorn jq" 

RUN apt update && \
	apt install -y $PERM_INSTALL && \
	apt clean && apt autoclean && apt autoremove && \
	rm -rf /var/lib/apt/lists/*

COPY start.sh /
COPY server.py /

RUN	chmod +x /start.sh
RUN	chmod +x /server.py

ENTRYPOINT ["/start.sh"]