FROM balenalib/%%BALENA_ARCH%%-debian:bookworm
LABEL maintainer="https://github.com/ketilmo"

ENV RADARBOX_KEY=

ARG PERM_INSTALL="tini" 

RUN apt update && \
	apt install -y $PERM_INSTALL && \
	apt clean && apt autoclean && apt autoremove && \
	rm -rf /var/lib/apt/lists/*

COPY start.sh /

RUN	chmod +x /start.sh

ENTRYPOINT ["/start.sh"]