{
 "title": "balena-ads-b — Services",
 "description": "Docker stats on all containers, including Supervisor",
 "tags": [
  "docker-balena",
  "linux-node-integration"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(container_device_short_uuid)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(container_service_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization by Services",
   "type": "gauge",
   "description": "Cumulative cpu time consumed in seconds.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (rate(container_cpu_utilization_ratio{container_device_short_uuid=~\"$instance\", container_service_name=~\"$service\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Memory Utilization by Services",
   "type": "gauge",
   "description": "Current memory usage in bytes, including all memory regardless of when it was accessed.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_total_bytes{container_device_short_uuid=~\"$instance\", container_service_name=~\"$service\"}) / avg(node_memory_MemTotal_bytes{instance=~\"$instance\"})"
    }
   ]
  },
  { "title": "Compute", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "Cpu time consumed in seconds by container.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (container_service_name) (rate(container_cpu_utilization_ratio{container_device_short_uuid=~\"$instance\", container_service_name=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "{{container_service_name}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Current memory usage in bytes, including all memory regardless of when it was accessed by container.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (container_service_name) (container_memory_usage_total_bytes{container_device_short_uuid=~\"$instance\", container_service_name=~\"$service\"})",
     "legendFormat": "{{container_service_name}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "description": "Cumulative count of bytes transmitted.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (container_service_name) (rate(container_network_io_usage_rx_bytes_total{container_device_short_uuid=~\"$instance\", container_service_name=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "{{container_service_name}} rx"
    },
    {
     "expr": "sum by (container_service_name) (rate(container_network_io_usage_tx_bytes_total{container_device_short_uuid=~\"$instance\", container_service_name=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "{{container_service_name}} tx"
    }
   ]
  }
 ]
}