# renovate: datasource=custom.klutchell-balena-tailscale depName=tailscale
ARG TAILSCALE_VERSION=1.98.5
FROM bh.cr/gh_klutchell/tailscale-%%BALENA_ARCH%%/$TAILSCALE_VERSION AS base
LABEL maintainer="https://github.com/ketilmo"

RUN apk add --no-cache tini curl

COPY start.sh /start.sh
COPY serve.json /etc/tailscale/serve.json

RUN chmod +x /start.sh

ENTRYPOINT ["/sbin/tini", "--", "/start.sh"]
