# renovate: datasource=docker depName=ghcr.io/ident-1090/ident
ARG IDENT_VERSION=v0.2.1

FROM ghcr.io/ident-1090/ident:${IDENT_VERSION}
LABEL maintainer="https://github.com/schubydoo"

USER root
RUN apk add --no-cache bash curl ca-certificates

COPY start.sh /start.sh
RUN chmod +x /start.sh

ENTRYPOINT ["/start.sh"]
