name: "Deploy to Balena - Draft"

on:
  workflow_dispatch:
  pull_request_target:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  build:
    name: "Deploy-to-Balena-Draft"
    runs-on: "ubuntu-latest"
    environment: ${{ (github.event_name == 'pull_request_target' && github.event.pull_request.user.login == 'renovate[bot]' && github.event.pull_request.head.repo.full_name == github.repository) && 'balena-draft-fleet-bots' || 'balena-draft-fleet' }}
    strategy:
      fail-fast: false
      matrix:
        architecture: ["aarch64", "amd64", "armv7hf"] # Not supported, but valid: rpi, i386, i386-nlp
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false

      - name: Build on Balena with ${{ matrix.architecture }} architecture (attempt 1)
        id: build1
        continue-on-error: true
        uses: balena-io/deploy-to-balena-action@638e3085dfe40b8c3cef2a34fe9d0874e572de4e # v2.2.0
        with:
          balena_token: ${{ secrets.BALENA_DRAFT_API_KEY }}
          fleet: ${{ vars.BALENA_DRAFT_FLEET }}-${{ matrix.architecture }}
          multi_dockerignore: true

      - name: Build on Balena with ${{ matrix.architecture }} architecture (attempt 2)
        id: build2
        if: steps.build1.outcome == 'failure'
        continue-on-error: true
        uses: balena-io/deploy-to-balena-action@638e3085dfe40b8c3cef2a34fe9d0874e572de4e # v2.2.0
        with:
          balena_token: ${{ secrets.BALENA_DRAFT_API_KEY }}
          fleet: ${{ vars.BALENA_DRAFT_FLEET }}-${{ matrix.architecture }}
          multi_dockerignore: true

      - name: Build on Balena with ${{ matrix.architecture }} architecture (attempt 3)
        id: build3
        if: steps.build1.outcome == 'failure' && steps.build2.outcome == 'failure'
        continue-on-error: true
        uses: balena-io/deploy-to-balena-action@638e3085dfe40b8c3cef2a34fe9d0874e572de4e # v2.2.0
        with:
          balena_token: ${{ secrets.BALENA_DRAFT_API_KEY }}
          fleet: ${{ vars.BALENA_DRAFT_FLEET }}-${{ matrix.architecture }}
          multi_dockerignore: true

      - name: Build on Balena with ${{ matrix.architecture }} architecture (attempt 4)
        id: build4
        if: steps.build1.outcome == 'failure' && steps.build2.outcome == 'failure' && steps.build3.outcome == 'failure'
        continue-on-error: true
        uses: balena-io/deploy-to-balena-action@638e3085dfe40b8c3cef2a34fe9d0874e572de4e # v2.2.0
        with:
          balena_token: ${{ secrets.BALENA_DRAFT_API_KEY }}
          fleet: ${{ vars.BALENA_DRAFT_FLEET }}-${{ matrix.architecture }}
          multi_dockerignore: true

      - name: Build on Balena with ${{ matrix.architecture }} architecture (attempt 5)
        if: steps.build1.outcome == 'failure' && steps.build2.outcome == 'failure' && steps.build3.outcome == 'failure' && steps.build4.outcome == 'failure'
        uses: balena-io/deploy-to-balena-action@638e3085dfe40b8c3cef2a34fe9d0874e572de4e # v2.2.0
        with:
          balena_token: ${{ secrets.BALENA_DRAFT_API_KEY }}
          fleet: ${{ vars.BALENA_DRAFT_FLEET }}-${{ matrix.architecture }}
          multi_dockerignore: true
