# renovate: datasource=docker depName=ghcr.io/schubydoo/autohupr versioning=docker
ARG AUTOHUPR_VERSION=0.5.10
FROM ghcr.io/schubydoo/autohupr:${AUTOHUPR_VERSION}
LABEL maintainer="https://github.com/ketilmo"
